### ISSUE TITLE
issue with installTFpython

### ISSUE THREAD

**Issue by Zockimonster** [diegommcc/SpatialDDLS#1]
Seems like there is an issue installing tensorflow within a conda environment using python 3.7 on windows...
even if installing it manually using conda within the environment, it seems not to work in RStudio...

#######################################################
 installTFpython(install.conda = TRUE)

=== Creating SpatialDDLS-env environment
+ *** "create" "--yes" "--name" "SpatialDDLS-env" "python==3.7.11" "--quiet" "-c" "conda-forge"
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: ***

  added / updated specs:
    - python==3.7.11

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2024.2.2-h56e8100_0 
  libsqlite          conda-forge/win-64::libsqlite-3.45.2-hcfcfb64_0 
  openssl            conda-forge/win-64::openssl-1.1.1w-hcfcfb64_0 
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
  python             pkgs/main/win-64::python-3.7.11-h6244533_0 
  setuptools         conda-forge/noarch::setuptools-69.0.3-pyhd8ed1ab_0 
  sqlite             conda-forge/win-64::sqlite-3.45.2-hcfcfb64_0 
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 
  vc                 conda-forge/win-64::vc-14.3-hcf57466_18 
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18 
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.38.33130-hcb4865c_18 
  wheel              conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

=== Installing tensorflow in SpatialDDLS-env environment
Error: Error during the installation. Please see the website of the package and/or the vignettes for more details
#############################################################

Would be nice, if I could just use an argument within the function to install python 3.6 within this environment, since this seems to be working: https://stackoverflow.com/questions/59905986/problem-installing-tensorflow-in-virtual-environment
(I think I should be able to change this on my own, but maybe there are some other's who are dealing with the same issue...)
##############################################################
PS:
if using
library(reticulate)
install_python(version = "3.6.8")
# restart r
library(reticulate)
use_python_version("3.6.8")
# installing tensorflow seems to be working,
# but there will be some other issues....
##############################################################
=== Installing tensorflow in SpatialDDLS-env environment

C:\Users\Eli\Documents>CALL "C:\Users\Eli\AppData\Local\r-miniconda\condabin\activate.bat" "SpatialDDLS-env" 

C:\Users\Eli\Documents>conda.bat activate "SpatialDDLS-env" 

(SpatialDDLS-env) C:\Users\Eli\Documents>"C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env/python.exe" -m pip install --upgrade --no-user "tensorflow-cpu==2.6.*" 
Collecting tensorflow-cpu==2.6.*
  Downloading tensorflow_cpu-2.6.5-cp37-cp37m-win_amd64.whl.metadata (2.9 kB)
Collecting numpy~=1.19.2 (from tensorflow-cpu==2.6.*)
  Downloading numpy-1.19.5-cp37-cp37m-win_amd64.whl.metadata (2.0 kB)
Collecting absl-py~=0.10 (from tensorflow-cpu==2.6.*)
  Downloading absl_py-0.15.0-py3-none-any.whl.metadata (2.4 kB)
Collecting astunparse~=1.6.3 (from tensorflow-cpu==2.6.*)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting clang~=5.0 (from tensorflow-cpu==2.6.*)
  Downloading clang-5.0.tar.gz (30 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting flatbuffers~=1.12.0 (from tensorflow-cpu==2.6.*)
  Downloading flatbuffers-1.12-py2.py3-none-any.whl.metadata (872 bytes)
Collecting google-pasta~=0.2 (from tensorflow-cpu==2.6.*)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py~=3.1.0 (from tensorflow-cpu==2.6.*)
  Downloading h5py-3.1.0-cp37-cp37m-win_amd64.whl.metadata (2.1 kB)
Collecting keras-preprocessing~=1.1.2 (from tensorflow-cpu==2.6.*)
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting opt-einsum~=3.3.0 (from tensorflow-cpu==2.6.*)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting protobuf<3.20,>=3.9.2 (from tensorflow-cpu==2.6.*)
  Downloading protobuf-3.19.6-cp37-cp37m-win_amd64.whl.metadata (807 bytes)
Collecting six~=1.15.0 (from tensorflow-cpu==2.6.*)
  Downloading six-1.15.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting termcolor~=1.1.0 (from tensorflow-cpu==2.6.*)
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting typing-extensions<3.11,>=3.7 (from tensorflow-cpu==2.6.*)
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: wheel~=0.35 in c:\users\eli\appdata\local\r-miniconda\envs\spatialddls-env\lib\site-packages (from tensorflow-cpu==2.6.*) (0.43.0)
Collecting wrapt~=1.12.1 (from tensorflow-cpu==2.6.*)
  Downloading wrapt-1.12.1.tar.gz (27 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting gast==0.4.0 (from tensorflow-cpu==2.6.*)
  Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting tensorboard<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Downloading tensorboard-2.6.0-py3-none-any.whl.metadata (1.9 kB)
Collecting tensorflow-estimator<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Downloading tensorflow_estimator-2.6.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting keras<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Downloading keras-2.6.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting grpcio<2.0,>=1.37.0 (from tensorflow-cpu==2.6.*)
  Downloading grpcio-1.62.1-cp37-cp37m-win_amd64.whl.metadata (4.2 kB)
Collecting cached-property (from h5py~=3.1.0->tensorflow-cpu==2.6.*)
  Downloading cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting google-auth<2,>=1.6.3 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading google_auth-1.35.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)
Collecting requests<3,>=2.21.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\eli\appdata\local\r-miniconda\envs\spatialddls-env\lib\site-packages (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*) (69.0.3)
Collecting tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl.metadata (1.1 kB)
Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl.metadata (873 bytes)
Collecting werkzeug>=0.11.15 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading Werkzeug-2.2.3-py3-none-any.whl.metadata (4.4 kB)
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading cachetools-4.2.4-py3-none-any.whl.metadata (4.8 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading requests_oauthlib-1.4.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting importlib-metadata>=4.4 (from markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl.metadata (4.9 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading charset_normalizer-3.3.2-cp37-cp37m-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug>=0.11.15->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading MarkupSafe-2.1.5-cp37-cp37m-win_amd64.whl.metadata (3.1 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading zipp-3.15.0-py3-none-any.whl.metadata (3.7 kB)
Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading pyasn1-0.5.1-py2.py3-none-any.whl.metadata (8.6 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Downloading tensorflow_cpu-2.6.5-cp37-cp37m-win_amd64.whl (241.3 MB)
   ---------------------------------------- 241.3/241.3 MB 3.7 MB/s eta 0:00:00
Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Downloading absl_py-0.15.0-py3-none-any.whl (132 kB)
   ---------------------------------------- 132.0/132.0 kB 7.6 MB/s eta 0:00:00
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading grpcio-1.62.1-cp37-cp37m-win_amd64.whl (4.6 MB)
   ---------------------------------------- 4.6/4.6 MB 5.7 MB/s eta 0:00:00
Downloading h5py-3.1.0-cp37-cp37m-win_amd64.whl (2.7 MB)
   ---------------------------------------- 2.7/2.7 MB 6.6 MB/s eta 0:00:00
Downloading keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
   ---------------------------------------- 1.3/1.3 MB 5.9 MB/s eta 0:00:00
Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
   ---------------------------------------- 42.6/42.6 kB ? eta 0:00:00
Downloading numpy-1.19.5-cp37-cp37m-win_amd64.whl (13.2 MB)
   ---------------------------------------- 13.2/13.2 MB 6.5 MB/s eta 0:00:00
Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Downloading protobuf-3.19.6-cp37-cp37m-win_amd64.whl (896 kB)
   ---------------------------------------- 896.6/896.6 kB 6.3 MB/s eta 0:00:00
Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Downloading tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
   ---------------------------------------- 5.6/5.6 MB 6.4 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
   ---------------------------------------- 462.9/462.9 kB 7.2 MB/s eta 0:00:00
Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
   ---------------------------------------- 152.9/152.9 kB 8.9 MB/s eta 0:00:00
Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Downloading Markdown-3.4.4-py3-none-any.whl (94 kB)
   ---------------------------------------- 94.2/94.2 kB 5.2 MB/s eta 0:00:00
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
   ---------------------------------------- 781.3/781.3 kB 7.1 MB/s eta 0:00:00
Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
   ---------------------------------------- 233.6/233.6 kB 7.0 MB/s eta 0:00:00
Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.3.2-cp37-cp37m-win_amd64.whl (98 kB)
   ---------------------------------------- 98.1/98.1 kB 5.5 MB/s eta 0:00:00
Using cached idna-3.6-py3-none-any.whl (61 kB)
Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Downloading MarkupSafe-2.1.5-cp37-cp37m-win_amd64.whl (17 kB)
Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
   --------------------------------------- 181.3/181.3 kB 10.7 MB/s eta 0:00:00
Downloading requests_oauthlib-1.4.0-py2.py3-none-any.whl (24 kB)
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
   ---------------------------------------- 124.2/124.2 kB 7.1 MB/s eta 0:00:00
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
   ---------------------------------------- 151.7/151.7 kB 9.4 MB/s eta 0:00:00
Downloading pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
   ---------------------------------------- 84.9/84.9 kB 4.7 MB/s eta 0:00:00
Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: clang, termcolor, wrapt
  Building wheel for clang (setup.py): started
  Building wheel for clang (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Eli\AppData\Local\Temp\pip-install-4txt48ao\clang_0da906abd1544030972640e05db84da7\setup.py", line 29, in <module>
          tests_require=['nose']
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for clang
  Running setup.py clean for clang
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Eli\AppData\Local\Temp\pip-install-4txt48ao\termcolor_3c4b60e813cb49f2a754e876955ff8a3\setup.py", line 53, in <module>
          'Topic :: Terminals'
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for termcolor
  Running setup.py clean for termcolor
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Eli\AppData\Local\Temp\pip-install-4txt48ao\wrapt_79a196c43a0f4603a3ad1a5c9f8a4145\setup.py", line 102, in <module>
          run_setup(with_extensions=True)
        File "C:\Users\Eli\AppData\Local\Temp\pip-install-4txt48ao\wrapt_79a196c43a0f4603a3ad1a5c9f8a4145\setup.py", line 72, in run_setup
          setup(**setup_kwargs_tmp)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\Eli\AppData\Local\r-miniconda\envs\SpatialDDLS-env\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wrapt
  Running setup.py clean for wrapt
Failed to build clang termcolor wrapt
ERROR: Could not build wheels for clang, termcolor, wrapt, which is required to install pyproject.toml-based projects
Error: Error during the installation. Please see the website of the package and/or the vignettes for more details
In addition: Warning message:
In shell(fi, intern = intern) :
  'C:\Users\Eli\AppData\Local\Temp\RtmpWk7x0I\file2a5034143820.bat' execution failed with error code 1
##################################################################
PPS: I removed lines around 490 in the functools.py file, now it seems to be working.... hopefully (  ;

Best regards.
Zockimonster

**Comment by diegommcc** [comment]
Hi @Zockimonster. Thanks a lot for your suggestion and pointing out this issue. The current version (installable from GitHub) includes two parameters to choose the python and tensorflow versions in the `installTFpython` function. For some reason, this combination of versions (python==3.7.11 and tensorflow==2.6-cpu) don’t work together anymore, although they used to.

Regarding your second problem, I see that it seems to be a problem of python <= 3.7 (https://github.com/NVIDIA/DeepLearningExamples/issues/1016), so one more reason to create a parameter to control the python version. If it works after removing those lines from the functools.py, great! But for a safer solution, using python 3.8 has worked for me. In fact, I've set this version as default in the `installTpython` function. 

Hope this helps!
Diego
